import Navbar from "@/components/custom/Header/Navbar"
import Footer from "@/components/custom/Footer";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <Navbar></Navbar>
      <div>{children}</div>
      <Footer></Footer>
    </>
  )
}
